/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KalendarRouteImport } from './routes/kalendar'
import { Route as KluboviRouteImport } from './routes/klubovi'
import { Route as KomisiiRouteImport } from './routes/komisii'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ObukiRouteImport } from './routes/obuki'
import { Route as PatekiDomoviRouteImport } from './routes/pateki-domovi'
import { Route as VestiRouteImport } from './routes/vesti'
import { Route as ZaNasRouteImport } from './routes/za-nas'
import { Route as KomisiiIndexRouteImport } from './routes/komisii.index'
import { Route as KomisiiSlugRouteImport } from './routes/komisii.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendarRoute = KalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const KluboviRoute = KluboviRouteImport.update({
  id: '/klubovi',
  path: '/klubovi',
  getParentRoute: () => rootRouteImport,
} as any)
const KomisiiRoute = KomisiiRouteImport.update({
  id: '/komisii',
  path: '/komisii',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ObukiRoute = ObukiRouteImport.update({
  id: '/obuki',
  path: '/obuki',
  getParentRoute: () => rootRouteImport,
} as any)
const PatekiDomoviRoute = PatekiDomoviRouteImport.update({
  id: '/pateki-domovi',
  path: '/pateki-domovi',
  getParentRoute: () => rootRouteImport,
} as any)
const VestiRoute = VestiRouteImport.update({
  id: '/vesti',
  path: '/vesti',
  getParentRoute: () => rootRouteImport,
} as any)
const ZaNasRoute = ZaNasRouteImport.update({
  id: '/za-nas',
  path: '/za-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KomisiiIndexRoute = KomisiiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KomisiiRoute,
} as any)
const KomisiiSlugRoute = KomisiiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KomisiiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kalendar': typeof KalendarRoute
  '/klubovi': typeof KluboviRoute
  '/komisii': typeof KomisiiRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/obuki': typeof ObukiRoute
  '/pateki-domovi': typeof PatekiDomoviRoute
  '/vesti': typeof VestiRoute
  '/za-nas': typeof ZaNasRoute
  '/komisii/$slug': typeof KomisiiSlugRoute
  '/komisii/': typeof KomisiiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kalendar': typeof KalendarRoute
  '/klubovi': typeof KluboviRoute
  '/kontakt': typeof KontaktRoute
  '/obuki': typeof ObukiRoute
  '/pateki-domovi': typeof PatekiDomoviRoute
  '/vesti': typeof VestiRoute
  '/za-nas': typeof ZaNasRoute
  '/komisii/$slug': typeof KomisiiSlugRoute
  '/komisii': typeof KomisiiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kalendar': typeof KalendarRoute
  '/klubovi': typeof KluboviRoute
  '/komisii': typeof KomisiiRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/obuki': typeof ObukiRoute
  '/pateki-domovi': typeof PatekiDomoviRoute
  '/vesti': typeof VestiRoute
  '/za-nas': typeof ZaNasRoute
  '/komisii/$slug': typeof KomisiiSlugRoute
  '/komisii/': typeof KomisiiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kalendar'
    | '/klubovi'
    | '/komisii'
    | '/kontakt'
    | '/obuki'
    | '/pateki-domovi'
    | '/vesti'
    | '/za-nas'
    | '/komisii/$slug'
    | '/komisii/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kalendar'
    | '/klubovi'
    | '/kontakt'
    | '/obuki'
    | '/pateki-domovi'
    | '/vesti'
    | '/za-nas'
    | '/komisii/$slug'
    | '/komisii'
  id:
    | '__root__'
    | '/'
    | '/kalendar'
    | '/klubovi'
    | '/komisii'
    | '/kontakt'
    | '/obuki'
    | '/pateki-domovi'
    | '/vesti'
    | '/za-nas'
    | '/komisii/$slug'
    | '/komisii/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KalendarRoute: typeof KalendarRoute
  KluboviRoute: typeof KluboviRoute
  KomisiiRoute: typeof KomisiiRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  ObukiRoute: typeof ObukiRoute
  PatekiDomoviRoute: typeof PatekiDomoviRoute
  VestiRoute: typeof VestiRoute
  ZaNasRoute: typeof ZaNasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendar': {
      id: '/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof KalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klubovi': {
      id: '/klubovi'
      path: '/klubovi'
      fullPath: '/klubovi'
      preLoaderRoute: typeof KluboviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komisii': {
      id: '/komisii'
      path: '/komisii'
      fullPath: '/komisii'
      preLoaderRoute: typeof KomisiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obuki': {
      id: '/obuki'
      path: '/obuki'
      fullPath: '/obuki'
      preLoaderRoute: typeof ObukiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pateki-domovi': {
      id: '/pateki-domovi'
      path: '/pateki-domovi'
      fullPath: '/pateki-domovi'
      preLoaderRoute: typeof PatekiDomoviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vesti': {
      id: '/vesti'
      path: '/vesti'
      fullPath: '/vesti'
      preLoaderRoute: typeof VestiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/za-nas': {
      id: '/za-nas'
      path: '/za-nas'
      fullPath: '/za-nas'
      preLoaderRoute: typeof ZaNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komisii/': {
      id: '/komisii/'
      path: '/'
      fullPath: '/komisii/'
      preLoaderRoute: typeof KomisiiIndexRouteImport
      parentRoute: typeof KomisiiRoute
    }
    '/komisii/$slug': {
      id: '/komisii/$slug'
      path: '/$slug'
      fullPath: '/komisii/$slug'
      preLoaderRoute: typeof KomisiiSlugRouteImport
      parentRoute: typeof KomisiiRoute
    }
  }
}

interface KomisiiRouteChildren {
  KomisiiSlugRoute: typeof KomisiiSlugRoute
  KomisiiIndexRoute: typeof KomisiiIndexRoute
}

const KomisiiRouteChildren: KomisiiRouteChildren = {
  KomisiiSlugRoute: KomisiiSlugRoute,
  KomisiiIndexRoute: KomisiiIndexRoute,
}

const KomisiiRouteWithChildren =
  KomisiiRoute._addFileChildren(KomisiiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KalendarRoute: KalendarRoute,
  KluboviRoute: KluboviRoute,
  KomisiiRoute: KomisiiRouteWithChildren,
  KontaktRoute: KontaktRoute,
  ObukiRoute: ObukiRoute,
  PatekiDomoviRoute: PatekiDomoviRoute,
  VestiRoute: VestiRoute,
  ZaNasRoute: ZaNasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
